language: java
jdk:
  - oraclejdk8

notifications:
  email: false

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - ./gradlew sendCoverageToCodacy
  - bash <(curl -s https://codecov.io/bash)