language: java
jdk:
  - oraclejdk8

notifications:
  email: false

before_install:
  - mkdir -p /opt/moss
  - openssl enc -aes256 -base64 -in ./libs/moss.pl.enc -out /opt/moss/moss.pl -k $MOSS_ENCR_KEY -d

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - ./gradlew sendCoverageToCodacy
  - bash <(curl -s https://codecov.io/bash)