version: '2.4'
services:
  backend:
    container_name: gitplag_backend
    image: nikstep/gitplag:${gitplag_version}
    ports:
      - 8090:8090
    volumes:
      - ${gitplag_directory}/data:/mnt/gitplag
    environment:
      GITPLAG_MOSS_ID: ${MOSS_ID}
      GITPLAG_DATASOURCE_URL: jdbc:postgresql://gitplag_database:5432/${POSTGRES_DB}
      GITPLAG_DATASOURCE_USERNAME: ${POSTGRES_USER}
      GITPLAG_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      GITPLAG_SERVER_URL: ${server_url}:8090
      GITPLAG_UI_URL: ${server_url}:${ui_port}
      GITPLAG_GITLAB_AUTH:
      GITPLAG_GITHUB_AUTH:
      GITPLAG_BITBUCKET_AUTH:
    depends_on:
      gitplag_database:
        condition: service_healthy
  frontend:
    container_name: gitplag_frontend
    image: nikstep/gitplag-ui:${gitplag_version}
    ports:
      - ${ui_port}:80
  gitplag_database:
    container_name: gitplag_database
    image: postgres:11.1
    volumes:
      - ${gitplag_directory}/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  data2graph:
    container_name: flaxo_data2graph
    image: flaxo/data2graph:${flaxo_version}
    ports:
      - 8088:80