spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${REDINK_DATASOURCE_USERNAME}
    password: ${REDINK_DATASOURCE_PASSWORD}
    url: ${REDINK_DATASOURCE_URL}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true

server:
  port: 80

redink:
  mossPath: ${MOSS_PATH}
  solutionsDir: ${SOLUTIONS_DIR}
  jplagResultDir: ${JPLAG_REPORT_DIR}
  analysisFilesDir: ${ANALYSIS_FILES_DIR}
  graphUrl: ${GRAPH_URL:#{'http://localhost:8088'}}?graph_url=
  serverUrl: ${SERVER_URL:#{'http://localhost'}}