spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${REDINK_DATASOURCE_USERNAME}
    password: ${REDINK_DATASOURCE_PASSWORD}
    url: ${REDINK_DATASOURCE_URL}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true

server:
  port: 80

redink:
  mossId: ${MOSS_ID}
  solutionsDir: ${SOLUTIONS_DIR}
  jplagResultDir: ${JPLAG_REPORT_DIR}
  serverUrl: ${SERVER_HTTP_URL}