spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${GITPLAG_DATASOURCE_USERNAME}
    password: ${GITPLAG_DATASOURCE_PASSWORD}
    url: ${GITPLAG_DATASOURCE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8090

gitplag:
  mossId: ${GITPLAG_MOSS_ID}
  solutionsDir: ${GITPLAG_SOLUTIONS_DIR}
  jplagResultDir: ${GITPLAG_JPLAG_REPORT_DIR}
  analysisFilesDir: ${GITPLAG_ANALYSIS_FILES_DIR}
  graphUrl: ${GITPLAG_GRAPH_URL:#{'http://localhost:8088'}}?graph_url=
  serverUrl: ${GITPLAG_SERVER_URL:#{'http://localhost'}}